# Generated by Django 5.2.14 on 2026-06-16 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('bank_movement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('glosa', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pagador', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='bank_movement_monto_positivo')],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contract_id', models.IntegerField(db_index=True)),
                ('mes_cobro', models.DateField()),
                ('monto_cobro', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('monto_cobro__gt', 0)), name='collection_monto_positivo')],
            },
        ),
        migrations.CreateModel(
            name='Abono',
            fields=[
                ('abono_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='tasks.bankmovement')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonos', to='tasks.collection')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='abono_monto_positivo')],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('devolucion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='tasks.bankmovement')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='devolucion_monto_positivo')],
            },
        ),
    ]
